### ISSUE TITLE
Error spawn ffprobe ENOENT 

### ISSUE THREAD

**Issue by aqueelaboobacker** [solana-mobile/dapp-publishing#284]
Getting this error while running `npx dapp-store validate` .
`spawn ffprobe ENOENT`

Running on node version  v18.16.0

Publishing Tools Version 0.9.2

<img width="399" alt="image" src="https://github.com/solana-mobile/dapp-publishing/assets/8208572/e609e0f0-cc81-4712-afaf-e3987b4c17a1">

**Comment by ankur2136** [comment]
Hi @aqueelaboobacker Can you provide a copy of `config.yaml` to repro and associated assets.

Also, can you tell us more about which OS and version you are running the tooling on.

**Comment by aqueelaboobacker** [comment]
macOS Sonoma Version 14.4.1

**Comment by aqueelaboobacker** [comment]
```
publisher:
  name: Ray Parker
  address: ""
  website: https://www.raiinmaker.com
  email: ray@raiinmaker.com
  media:
    - purpose: icon
      uri: ./media/app_icon.png
app:
  name: Raiinmaker
  address: ""
  android_package: com.raiinmaker.app
  urls:
    license_url: https://coiin.ai/terms-of-use
    copyright_url: https://coiin.ai/terms-of-use
    privacy_policy_url: https://www.raiinmaker.com/privacy-policy
    website: https://www.raiinmaker.com
  media:
    - purpose: icon
      uri: ./media/app_icon.png
release:
  address: ""
  media:
    - purpose: icon
      uri: ./media/app_icon.png
    - purpose: screenshot
      uri: ./media/screen-1.png
    - purpose: screenshot
      uri: ./media/screen-2.png
    - purpose: screenshot
      uri: ./media/screen-3.png
    - purpose: screenshot
      uri: ./media/screen-4.png
    - purpose: video
      uri: ./media/video.mp4
  files:
    - purpose: install
      uri: ./files/app-release.apk
  catalog:
    en-US:
      name: Raiinmaker
      short_description: Train and Earn
      long_description: Raiinmaker is a Web3 and AI application powered by the Raiinmaker Network Protocol that democratizes the power of advanced AI technologies, making them accessible to everyone. Become a network validator as well as contribute to training new AI models while you earn rewards.
      new_in_version: First release
solana_mobile_dapp_publisher_portal:
  testing_instructions: Use the following username and password

```
